<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'future');
phutil_require_module('phutil', 'future/http/status/http');
phutil_require_module('phutil', 'future/http/status/parse');
phutil_require_module('phutil', 'utils');


phutil_require_source('BaseHTTPFuture.php');
