<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'PhutilTestClassA' => 'test/PhutilTestClassA.php',
    'PhutilTestClassB' => 'test/PhutilTestClassB.php',
  ),
  'function' => array(),
  'xmap' => array(
    'PhutilTestClassB' => 'PhutilTestClassA',
  ),
));
