<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'aphront/mapper');
phutil_require_module('phutil', 'autoload');
phutil_require_module('phutil', 'utils');


phutil_require_source('AphrontApplicationConfiguration.php');
