<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'future/aws/exception');
phutil_require_module('phutil', 'future/http/http');
phutil_require_module('phutil', 'future/proxy');
phutil_require_module('phutil', 'parser/uri');


phutil_require_source('PhutilAWSFuture.php');
