<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'filesystem');
phutil_require_module('phutil', 'future/http/base');
phutil_require_module('phutil', 'future/http/status/curl');
phutil_require_module('phutil', 'moduleutils');


phutil_require_source('HTTPSFuture.php');
