<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'parser/argument/spec');


phutil_require_source('PhutilArgumentWorkflow.php');
