<?php

/*
 * Copyright 2012 Facebook, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @group markup
 * @stable
 */
abstract class PhutilMarkupEngine {

  /**
   * Set a configuration parameter which the engine can read to customize how
   * the text is marked up. This is a generic interface; consult the
   * documentation for specific rules and blocks for what options are available
   * for configuration.
   *
   * @param   string  Key to set in the configuration dictionary.
   * @param   string  Value to set.
   * @return  this
   */
  abstract public function setConfig($key, $value);

  /**
   * After text has been marked up with markupText(), you can retrieve any
   * metadata the markup process generated by calling this method. This is
   * a generic interface that allows rules to export extra information about
   * text; consult the documentation for specific rules and blocks to see what
   * metadata may be available in your configuration.
   *
   * @param   string  Key to retrieve from metadata.
   * @param   mixed   Default value to return if the key is not available.
   * @return  mixed   Metadata property, or default value.
   */
  abstract public function getTextMetadata($key, $default = null);

  abstract public function markupText($text);
}
