<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'aphront/applicationconfiguration');
phutil_require_module('phutil', 'aphront/request');


phutil_require_source('AphrontDefaultApplicationConfiguration.php');
