<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'console');
phutil_require_module('phutil', 'filesystem');
phutil_require_module('phutil', 'parser/argument/exception/specification');
phutil_require_module('phutil', 'parser/argument/exception/usage');
phutil_require_module('phutil', 'parser/argument/spec');
phutil_require_module('phutil', 'serviceprofiler');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhutilArgumentParser.php');
