<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'markup/syntax/engine/base');
phutil_require_module('phutil', 'markup/syntax/highlighter/console');
phutil_require_module('phutil', 'markup/syntax/highlighter/default');
phutil_require_module('phutil', 'markup/syntax/highlighter/diviner');
phutil_require_module('phutil', 'markup/syntax/highlighter/pygments');
phutil_require_module('phutil', 'markup/syntax/highlighter/rainbow');
phutil_require_module('phutil', 'markup/syntax/highlighter/xhpast');
phutil_require_module('phutil', 'parser/languageguesser');
phutil_require_module('phutil', 'parser/xhpast/bin');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhutilDefaultSyntaxHighlighterEngine.php');
