<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'future/exec');
phutil_require_module('phutil', 'future/immediate');
phutil_require_module('phutil', 'markup');
phutil_require_module('phutil', 'markup/syntax/engine/base');
phutil_require_module('phutil', 'markup/syntax/engine/default/future');
phutil_require_module('phutil', 'markup/syntax/highlighter/xhpast');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhutilDefaultSyntaxHighlighterEngine.php');
