<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'markup/engine/remarkup/blockrule/base');


phutil_require_source('PhutilRemarkupEngineRemarkupQuotesBlockRule.php');
