<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'moduleutils');
phutil_require_module('phutil', 'symbols');


phutil_require_source('deprecated.php');
