<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'future/immediate');
phutil_require_module('phutil', 'markup');
phutil_require_module('phutil', 'markup/syntax/highlighter/default');
phutil_require_module('phutil', 'markup/syntax/highlighter/pygments');
phutil_require_module('phutil', 'parser/xhpast/api/tree');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhutilXHPASTSyntaxHighlighter.php');
