<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'daemon/torture/base');


phutil_require_source('PhutilSaturateStdoutDaemon.php');
