<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'future/aws/base');


phutil_require_source('PhutilAWSEC2Future.php');
