<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'storage/exception/recoverable');


phutil_require_source('PhutilQueryConnectionLostException.php');
