<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'future/exec');
phutil_require_module('phutil', 'markup/syntax/highlighter/default');
phutil_require_module('phutil', 'markup/syntax/highlighter/pygments/future');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhutilPygmentsSyntaxHighlighter.php');
