<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'parser/argument/exception/specification');


phutil_require_source('PhutilArgumentSpecification.php');
